/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=.dev.vars.example --include-runtime=false` (hash: e14da111618444628363ed10c9270dec)
interface __BaseEnv_Env {
	PORTAL_KV: KVNamespace;
	REPORT_RATE_LIMITER: RateLimit;
	GITHUB_REPOSITORY: "25thplaymaking/BannerlordCoop-FriendEdition";
	GITHUB_TOKEN: string;
	PUBLISH_TOKEN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GITHUB_REPOSITORY" | "GITHUB_TOKEN" | "PUBLISH_TOKEN">> {}
}
