using Common;
using Common.Logging;
using Common.Messaging;
using Common.Network;
using Coop.Core.Server.Services.MobileParties.Messages;
using GameInterface.Services.ObjectManager;
using GameInterface.Services.Players;
using GameInterface.Utils.NetworkEvents;
using HarmonyLib;
using Serilog;
using System;
using System.Collections.Generic;
using System.Reflection;
using TaleWorlds.CampaignSystem;
using TaleWorlds.CampaignSystem.Party;
using TaleWorlds.CampaignSystem.Roster;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.Library;

namespace Coop.Core.Server.Services.Replication;

/// <summary>
/// Holds replication messages about objects no player is near, releasing them when someone comes close.
/// </summary>
/// <remarks>
/// This sits on <c>CoopNetworkBase.SendAll(IMessage)</c>, the one point every broadcast passes through,
/// which is why it can cover the whole replication surface without editing 500-odd send sites.
/// <para>
/// Only messages that are safe to hold are held: a whole-member state set
/// (<c>*_SetNetworkMessage</c>, generated by AutoSync's set templates) and the party-behaviour
/// snapshot. Both are idempotent — the newest one fully describes the state — so keeping only the
/// latest per object per message type is lossless in the end state, which is exactly what a client
/// needs when it finally looks. Deltas, adds, removes, clears and dictionary upserts are NOT held:
/// they are order- and history-dependent, and collapsing them would lose data.
/// </para>
/// <para>
/// Held is not dropped. Everything buffered is sent from <see cref="FlushDue"/> the moment its object
/// becomes relevant, and unconditionally once <see cref="MaximumHold"/> passes, so the worst case is a
/// short delay on something nobody can see. Anything this cannot classify or position is sent
/// immediately — a wrongly held message would be a desync, a wrongly sent one is only a packet.
/// </para>
/// </remarks>
public class ReplicationRelevanceFilter : ISendRelevanceFilter
{
    private static readonly ILogger Logger = LogManager.GetLogger<ReplicationRelevanceFilter>();

    /// <summary>Turns holding off without a redeploy, for A/B against the packet profile.</summary>
    public static bool Enabled = true;

    /// <summary>
    /// How far from a player an object still counts as observable, in campaign map units. Party
    /// spotting range is single digits, so this is an order of magnitude more than a client can see,
    /// while Europe 1100 spans roughly 1,405 x 894 units. Erring high only means holding less.
    /// </summary>
    public static float RelevanceRadius = 100f;

    /// <summary>Longest anything is held, however irrelevant it looks. A safety net, not a schedule.</summary>
    public static TimeSpan MaximumHold = TimeSpan.FromSeconds(10);

    /// <summary>
    /// How often held objects are re-evaluated. Relevance changes at riding pace, so a few times a
    /// second is far more often than it can matter, and it keeps the sweep off every network poll.
    /// </summary>
    private static readonly TimeSpan EvaluateInterval = TimeSpan.FromMilliseconds(250);

    private static readonly TimeSpan ReportInterval = TimeSpan.FromSeconds(60);

    private sealed class HeldObject
    {
        public Type InstanceType;
        public string InstanceId;
        public DateTime FirstHeldUtc;

        // Latest message per message type. Every message that reaches here is idempotent, so an older
        // one of the same type is genuinely superseded rather than merely newer.
        public readonly Dictionary<Type, IMessage> Latest = new Dictionary<Type, IMessage>();
    }

    private readonly IObjectManager objectManager;
    private readonly IPlayerManager playerManager;

    private readonly Dictionary<string, HeldObject> held = new Dictionary<string, HeldObject>(StringComparer.Ordinal);
    private readonly List<Vec2> playerPositions = new List<Vec2>();
    private readonly object gate = new object();

    private DateTime nextEvaluateUtc = DateTime.MinValue;
    private DateTime nextReportUtc = DateTime.MinValue;
    private long sentCount;
    private long heldCount;
    private long releasedCount;

    private static readonly PropertyInfo TroopRosterOwnerParty =
        AccessTools.Property(typeof(TroopRoster), "OwnerParty");

    // Reached by reflection rather than directly: this assembly links the stock TaleWorlds references,
    // where the AI's back-reference to its party is not public.
    private static readonly FieldInfo MobilePartyAiOwner =
        AccessTools.Field(typeof(MobilePartyAi), "_mobileParty");

    /// <summary>
    /// Hand-written messages that carry a FULL snapshot scoped to one party, mapped to the field naming
    /// that party. They are idempotent for the same reason the generated sets are — the newest one
    /// replaces the whole thing — so the same latest-wins hold applies. Matched by name because these
    /// types are internal to GameInterface; add a line here to cover another.
    /// </summary>
    private static readonly Dictionary<string, string> PartyScopedSnapshots =
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            { "GameInterface.Services.Caravans.Messages.NetworkUpdateTradeActionLogsForParty", "MobilePartyId" },
        };

    // Resolved once per message type; reflection on the hot send path otherwise.
    private static readonly Dictionary<Type, FieldInfo> PartyIdFields = new Dictionary<Type, FieldInfo>();
    private static readonly object PartyIdFieldsGate = new object();

    private static FieldInfo GetPartyIdField(Type messageType)
    {
        lock (PartyIdFieldsGate)
        {
            if (PartyIdFields.TryGetValue(messageType, out FieldInfo cached)) return cached;

            FieldInfo resolved = null;
            if (PartyScopedSnapshots.TryGetValue(messageType.FullName ?? string.Empty, out string fieldName))
            {
                resolved = AccessTools.Field(messageType, fieldName);
            }

            PartyIdFields[messageType] = resolved;
            return resolved;
        }
    }

    public ReplicationRelevanceFilter(IObjectManager objectManager, IPlayerManager playerManager)
    {
        this.objectManager = objectManager;
        this.playerManager = playerManager;
    }

    public bool ShouldSendNow(IMessage message)
    {
        if (!Enabled || !ModInformation.IsServer || Campaign.Current == null) return true;

        if (!TryGetSubject(message, out Type instanceType, out string instanceId, out Vec2 knownPosition,
                out bool positionKnown))
        {
            return true;
        }

        RefreshPlayerPositions();
        if (playerPositions.Count == 0) return true;

        if (!positionKnown && !TryGetPosition(instanceType, instanceId, out knownPosition)) return true;

        if (IsNearAnyPlayer(knownPosition))
        {
            sentCount++;
            return true;
        }

        string subjectKey = instanceType.Name + ":" + instanceId;
        lock (gate)
        {
            if (!held.TryGetValue(subjectKey, out HeldObject entry))
            {
                entry = new HeldObject
                {
                    InstanceType = instanceType,
                    InstanceId = instanceId,
                    FirstHeldUtc = DateTime.UtcNow,
                };
                held[subjectKey] = entry;
            }

            entry.Latest[message.GetType()] = message;
        }

        heldCount++;
        return false;
    }

    public void FlushDue(INetwork network)
    {
        if (network == null) return;

        DateTime now = DateTime.UtcNow;
        if (now < nextEvaluateUtc)
        {
            Report(now);
            return;
        }
        nextEvaluateUtc = now + EvaluateInterval;

        RefreshPlayerPositions();

        List<IMessage> toSend = null;
        lock (gate)
        {
            if (held.Count == 0)
            {
                Report(now);
                return;
            }

            List<string> released = null;
            foreach (var pair in held)
            {
                HeldObject entry = pair.Value;

                bool expired = now - entry.FirstHeldUtc >= MaximumHold;
                bool relevant = false;

                if (!expired)
                {
                    // No players means nobody to be far from; release rather than accumulate a backlog
                    // that would land on whoever joins next.
                    relevant = playerPositions.Count == 0 ||
                        (TryGetPosition(entry.InstanceType, entry.InstanceId, out Vec2 position)
                            ? IsNearAnyPlayer(position)
                            : true);
                }

                if (!expired && !relevant) continue;

                (toSend ??= new List<IMessage>()).AddRange(entry.Latest.Values);
                (released ??= new List<string>()).Add(pair.Key);
            }

            if (released != null)
            {
                foreach (string key in released) held.Remove(key);
            }
        }

        if (toSend != null)
        {
            releasedCount += toSend.Count;

            // Sent outside the lock: SendAll re-enters this filter, which would deadlock on a held lock.
            // Re-entry is harmless now — these objects are relevant, so ShouldSendNow lets them straight
            // through, and an expired one is at worst held again with a fresh clock.
            foreach (IMessage message in toSend) network.SendAll(message);
        }

        Report(now);
    }

    private void Report(DateTime now)
    {
        if (nextReportUtc == DateTime.MinValue)
        {
            nextReportUtc = now + ReportInterval;
            return;
        }
        if (now < nextReportUtc) return;
        nextReportUtc = now + ReportInterval;

        long considered = sentCount + heldCount;
        if (considered == 0) return;

        int outstanding;
        lock (gate) outstanding = held.Count;

        Logger.Information(
            "[Relevance] {Held} of {Considered} messages held ({Percent:N0}%), {Released} released, " +
            "{Outstanding} objects still held, radius {Radius:N0}",
            heldCount, considered, 100.0 * heldCount / considered, releasedCount, outstanding, RelevanceRadius);

        sentCount = 0;
        heldCount = 0;
        releasedCount = 0;
    }

    private bool IsNearAnyPlayer(Vec2 position)
    {
        float radiusSquared = RelevanceRadius * RelevanceRadius;
        for (int i = 0; i < playerPositions.Count; i++)
        {
            if (playerPositions[i].DistanceSquared(position) <= radiusSquared) return true;
        }
        return false;
    }

    private void RefreshPlayerPositions()
    {
        playerPositions.Clear();

        foreach (var player in playerManager.Players)
        {
            if (string.IsNullOrEmpty(player?.MobilePartyId)) continue;
            if (!objectManager.TryGetObject<MobileParty>(player.MobilePartyId, out var party)) continue;
            if (party == null || !party.IsActive) continue;

            playerPositions.Add(party.Position.ToVec2());
        }
    }

    /// <summary>
    /// Identifies what a message is about, and whether it is one of the message shapes that can be held.
    /// </summary>
    public static bool TryGetSubject(
        IMessage message, out Type instanceType, out string instanceId, out Vec2 position, out bool positionKnown)
    {
        instanceType = null;
        instanceId = null;
        position = default;
        positionKnown = false;

        // The party-behaviour snapshot carries its own position, so it needs no lookup at all. It fully
        // describes the party's current behaviour, so the newest one supersedes the rest.
        if (message is NetworkUpdatePartyBehavior behavior)
        {
            if (string.IsNullOrEmpty(behavior.BehaviorUpdateData.MobilePartyId)) return false;

            instanceType = typeof(MobileParty);
            instanceId = behavior.BehaviorUpdateData.MobilePartyId;
            position = behavior.BehaviorUpdateData.PartyPosition.ToVec2();
            positionKnown = true;
            return true;
        }

        FieldInfo partyIdField = GetPartyIdField(message.GetType());
        if (partyIdField != null)
        {
            if (!(partyIdField.GetValue(message) is string partyId) || string.IsNullOrEmpty(partyId)) return false;

            instanceType = typeof(MobileParty);
            instanceId = partyId;
            return true;
        }

        if (message is not IInstanceScopedNetworkEvent scoped) return false;

        // Only whole-member sets. Add/Remove/Change/Clear/Upsert describe a step rather than a state, so
        // keeping "the latest" would throw away the steps in between.
        if (!message.GetType().Name.EndsWith("_SetNetworkMessage", StringComparison.Ordinal)) return false;

        if (string.IsNullOrEmpty(scoped.InstanceId) || scoped.InstanceType == null) return false;

        instanceType = scoped.InstanceType;
        instanceId = scoped.InstanceId;
        return true;
    }

    /// <summary>
    /// Where an object is on the campaign map, for the types worth filtering. Anything else returns
    /// false and is sent immediately.
    /// </summary>
    private bool TryGetPosition(Type instanceType, string compactId, out Vec2 position)
    {
        position = default;
        if (instanceType == null || string.IsNullOrEmpty(compactId)) return false;

        string fullId = instanceType.Name + "_" + compactId;

        if (instanceType == typeof(MobileParty))
        {
            if (!objectManager.TryGetObject<MobileParty>(fullId, out var party) || party == null) return false;
            position = party.Position.ToVec2();
            return true;
        }

        if (instanceType == typeof(Settlement))
        {
            if (!objectManager.TryGetObject<Settlement>(fullId, out var settlement) || settlement == null) return false;
            position = settlement.Position.ToVec2();
            return true;
        }

        if (instanceType == typeof(PartyBase))
        {
            if (!objectManager.TryGetObject<PartyBase>(fullId, out var partyBase) || partyBase == null) return false;
            return TryGetPartyBasePosition(partyBase, out position);
        }

        if (instanceType == typeof(MobilePartyAi))
        {
            if (!objectManager.TryGetObject<MobilePartyAi>(fullId, out var ai) || ai == null) return false;
            if (!(MobilePartyAiOwner?.GetValue(ai) is MobileParty owner)) return false;
            position = owner.Position.ToVec2();
            return true;
        }

        if (instanceType == typeof(TroopRoster))
        {
            if (!objectManager.TryGetObject<TroopRoster>(fullId, out var roster) || roster == null) return false;
            if (!(TroopRosterOwnerParty?.GetValue(roster) is PartyBase owner)) return false;
            return TryGetPartyBasePosition(owner, out position);
        }

        if (instanceType == typeof(Hero))
        {
            if (!objectManager.TryGetObject<Hero>(fullId, out var hero) || hero == null) return false;
            return TryGetHeroPosition(hero, out position);
        }

        if (instanceType == typeof(Town))
        {
            if (!objectManager.TryGetObject<Town>(fullId, out var town) || town?.Settlement == null) return false;
            position = town.Settlement.Position.ToVec2();
            return true;
        }

        if (instanceType == typeof(Village))
        {
            if (!objectManager.TryGetObject<Village>(fullId, out var village) || village?.Settlement == null) return false;
            position = village.Settlement.Position.ToVec2();
            return true;
        }

        return false;
    }

    private static bool TryGetPartyBasePosition(PartyBase party, out Vec2 position)
    {
        position = default;
        if (party == null) return false;

        if (party.IsMobile && party.MobileParty != null)
        {
            position = party.MobileParty.Position.ToVec2();
            return true;
        }

        if (party.IsSettlement && party.Settlement != null)
        {
            position = party.Settlement.Position.ToVec2();
            return true;
        }

        return false;
    }

    private static bool TryGetHeroPosition(Hero hero, out Vec2 position)
    {
        position = default;
        if (hero == null) return false;

        if (hero.PartyBelongedTo != null)
        {
            position = hero.PartyBelongedTo.Position.ToVec2();
            return true;
        }

        if (hero.CurrentSettlement != null)
        {
            position = hero.CurrentSettlement.Position.ToVec2();
            return true;
        }

        // A hero with no party and no settlement (prisoner, wanderer between states) has no place on the
        // map; sending is cheaper than reasoning about where they might turn up.
        return false;
    }
}
